"""remove severity and status column

Revision ID: 603ab33ba518
Revises: e4d57ad74fd2
Create Date: 2025-06-16 15:53:56.321609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603ab33ba518'
down_revision: Union[str, None] = 'e4d57ad74fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('damage_reports', 'severity')
    op.drop_column('damage_reports', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('damage_reports', sa.Column('status', sa.VARCHAR(length=11), nullable=False))
    op.add_column('damage_reports', sa.Column('severity', sa.VARCHAR(length=8), nullable=False))
    # ### end Alembic commands ###
