"""init migration

Revision ID: db46ec061ae9
Revises: 
Create Date: 2025-05-23 07:20:03.608480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db46ec061ae9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('damage_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='damageseverityenum_dr', inherit_schema=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_review', 'in_progress', 'completed', name='reportstatusenum_dr', inherit_schema=True), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('date_reported', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damage_reports_damage_type'), 'damage_reports', ['damage_type'], unique=False)
    op.create_index(op.f('ix_damage_reports_id'), 'damage_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_damage_reports_id'), table_name='damage_reports')
    op.drop_index(op.f('ix_damage_reports_damage_type'), table_name='damage_reports')
    op.drop_table('damage_reports')
    # ### end Alembic commands ###
